/**
 * Datos mock para demostración cuando la API no está disponible
 */

import { Producto, Categoria, Tenant } from '@/types';

export const mockTenant: Tenant = {
  id: 'demo-tenant-1',
  nombre: 'Urban Style',
  slug: 'urban-style',
  descripcion: 'Moda urbana y contemporánea para jóvenes',
  logoUrl: undefined,
  bannerUrl: undefined,
  whatsappNumero: '+51999999999',
  email: 'contacto@urbanstyle.com',
  direccion: 'Av. Principal 123, Lima',
  ciudad: 'Lima',
  pais: 'Perú',
  moneda: 'PEN',
  activo: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const mockCategorias: Categoria[] = [
  {
    id: 'cat-1',
    tenantId: 'demo-tenant-1',
    nombre: 'Poleras',
    slug: 'poleras',
    descripcion: 'Poleras y camisetas urbanas',
    orden: 1,
    activo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    tenantId: 'demo-tenant-1',
    nombre: 'Pantalones',
    slug: 'pantalones',
    descripcion: 'Pantalones jeans y joggers',
    orden: 2,
    activo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    tenantId: 'demo-tenant-1',
    nombre: 'Accesorios',
    slug: 'accesorios',
    descripcion: 'Accesorios de moda',
    orden: 3,
    activo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockProductos: Producto[] = [
  {
    id: 'prod-1',
    tenantId: 'demo-tenant-1',
    categoriaId: 'cat-1',
    nombre: 'Polera Oversize Black',
    slug: 'polera-oversize-black',
    descripcion: 'Polera oversize 100% algodón, corte urbano. Perfecta para looks casuales con estilo.',
    precio: 89.90,
    precioOferta: 79.90,
    imagenPrincipal: undefined,
    activo: true,
    destacado: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variantes: [
      { id: 'var-1-1', productoId: 'prod-1', talla: 'S', color: 'Negro', colorHex: '#000000', stock: 15, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-1-2', productoId: 'prod-1', talla: 'M', color: 'Negro', colorHex: '#000000', stock: 20, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-1-3', productoId: 'prod-1', talla: 'L', color: 'Negro', colorHex: '#000000', stock: 12, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-1-4', productoId: 'prod-1', talla: 'XL', color: 'Negro', colorHex: '#000000', stock: 8, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    ],
    _count: { variantes: 4 },
  },
  {
    id: 'prod-2',
    tenantId: 'demo-tenant-1',
    categoriaId: 'cat-1',
    nombre: 'Polera Graphic White',
    slug: 'polera-graphic-white',
    descripcion: 'Polera con estampado gráfico frontal. Diseño exclusivo de la temporada.',
    precio: 79.90,
    precioOferta: undefined,
    imagenPrincipal: undefined,
    activo: true,
    destacado: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variantes: [
      { id: 'var-2-1', productoId: 'prod-2', talla: 'S', color: 'Blanco', colorHex: '#FFFFFF', stock: 10, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-2-2', productoId: 'prod-2', talla: 'M', color: 'Blanco', colorHex: '#FFFFFF', stock: 18, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-2-3', productoId: 'prod-2', talla: 'L', color: 'Blanco', colorHex: '#FFFFFF', stock: 15, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    ],
    _count: { variantes: 3 },
  },
  {
    id: 'prod-3',
    tenantId: 'demo-tenant-1',
    categoriaId: 'cat-1',
    nombre: 'Polera Hoodie Gray',
    slug: 'polera-hoodie-gray',
    descripcion: 'Hoodie urbano con capucha. Ideal para temporadas frías.',
    precio: 129.90,
    precioOferta: 109.90,
    imagenPrincipal: undefined,
    activo: true,
    destacado: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variantes: [
      { id: 'var-3-1', productoId: 'prod-3', talla: 'M', color: 'Gris', colorHex: '#808080', stock: 12, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-3-2', productoId: 'prod-3', talla: 'L', color: 'Gris', colorHex: '#808080', stock: 10, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-3-3', productoId: 'prod-3', talla: 'XL', color: 'Gris', colorHex: '#808080', stock: 6, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    ],
    _count: { variantes: 3 },
  },
  {
    id: 'prod-4',
    tenantId: 'demo-tenant-1',
    categoriaId: 'cat-2',
    nombre: 'Jean Slim Fit Dark',
    slug: 'jean-slim-fit-dark',
    descripcion: 'Jean slim fit con lavado oscuro. Corte moderno y cómodo.',
    precio: 149.90,
    precioOferta: undefined,
    imagenPrincipal: undefined,
    activo: true,
    destacado: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variantes: [
      { id: 'var-4-1', productoId: 'prod-4', talla: '28', color: 'Azul Oscuro', colorHex: '#1a237e', stock: 8, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-4-2', productoId: 'prod-4', talla: '30', color: 'Azul Oscuro', colorHex: '#1a237e', stock: 12, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-4-3', productoId: 'prod-4', talla: '32', color: 'Azul Oscuro', colorHex: '#1a237e', stock: 15, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-4-4', productoId: 'prod-4', talla: '34', color: 'Azul Oscuro', colorHex: '#1a237e', stock: 6, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    ],
    _count: { variantes: 4 },
  },
  {
    id: 'prod-5',
    tenantId: 'demo-tenant-1',
    categoriaId: 'cat-2',
    nombre: 'Jogger Cargo Olive',
    slug: 'jogger-cargo-olive',
    descripcion: 'Jogger cargo con bolsillos laterales. Estilo militar urbano.',
    precio: 119.90,
    precioOferta: 99.90,
    imagenPrincipal: undefined,
    activo: true,
    destacado: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variantes: [
      { id: 'var-5-1', productoId: 'prod-5', talla: 'S', color: 'Verde Oliva', colorHex: '#556b2f', stock: 10, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-5-2', productoId: 'prod-5', talla: 'M', color: 'Verde Oliva', colorHex: '#556b2f', stock: 14, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-5-3', productoId: 'prod-5', talla: 'L', color: 'Verde Oliva', colorHex: '#556b2f', stock: 8, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    ],
    _count: { variantes: 3 },
  },
  {
    id: 'prod-6',
    tenantId: 'demo-tenant-1',
    categoriaId: 'cat-3',
    nombre: 'Gorro Beanie Black',
    slug: 'gorro-beanie-black',
    descripcion: 'Gorro beanie clásico. Accesorio esencial para cualquier look.',
    precio: 39.90,
    precioOferta: undefined,
    imagenPrincipal: undefined,
    activo: true,
    destacado: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variantes: [
      { id: 'var-6-1', productoId: 'prod-6', talla: 'Única', color: 'Negro', colorHex: '#000000', stock: 25, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'var-6-2', productoId: 'prod-6', talla: 'Única', color: 'Gris', colorHex: '#808080', stock: 20, activo: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    ],
    _count: { variantes: 2 },
  },
];
